### ISSUE TITLE
More accessible format for slides and code examples

### ISSUE THREAD

**Issue by sscarduzio** [noelmarkham/lambdadays-2015#4]
Hi Noel, I really enjoyed the presentation and I keep on coming back to this material to take inspiration on the way you use Scalaz Monad. However, every time I have to clone the project and start sbt. It just takes forever!

Do you happen to have a backup static version of the slides, say in markdown or pdf, ppt?

**Comment by sscarduzio** [comment]
Nevermind, I found this: https://github.com/noelmarkham/scalaexchange-2015/blob/master/src/test/scala/com/noelmarkham/lambdadays/WiringTest.scala

**Comment by noelmarkham** [comment]
Sorry, I never made a "hard copy" of my slides, but it looks like you've found what you needed. Let me know if you need a hand with anything!
